import type React from "react"
import type { Metadata } from "next"
import { headers } from "next/headers"
import { cookieToInitialState } from "wagmi"

import "./globals.css"

import { Geist, Geist_Mono, Geist as V0_Font_Geist, Geist_Mono as V0_Font_Geist_Mono, Source_Serif_4 as V0_Font_Source_Serif_4 } from 'next/font/google'
import { Providers } from "./providers"
import { config } from "@/lib/wagmi/config"

// Initialize fonts
const _geist = V0_Font_Geist({ subsets: ['latin'], weight: ["100","200","300","400","500","600","700","800","900"] })
const _geistMono = V0_Font_Geist_Mono({ subsets: ['latin'], weight: ["100","200","300","400","500","600","700","800","900"] })
const _sourceSerif_4 = V0_Font_Source_Serif_4({ subsets: ['latin'], weight: ["200","300","400","500","600","700","800","900"] })

const geistSans = Geist({ subsets: ["latin"] })
const geistMono = Geist_Mono({ subsets: ["latin"] })

// Site configuration for SEO
const siteConfig = {
  name: "Hyperfolio",
  title: "Hyperfolio - DeFi Portfolio Tracker for HyperEVM",
  description: "Track your HyperEVM portfolio across multiple wallets. Monitor tokens, NFTs, DeFi positions, and transactions in real-time on the Hyperliquid ecosystem.",
  url: "https://hyperfolio.xyz",
  twitterHandle: "@stableAPY",
  keywords: [
    "HyperEVM",
    "Hyperliquid",
    "DeFi",
    "Portfolio Tracker",
    "Crypto Portfolio",
    "NFT Tracker",
    "Wallet Tracker",
    "Multi-wallet",
    "Token Tracking",
    "DeFi Dashboard",
    "Hyperbeat",
    "HYPE",
  ],
}

export const metadata: Metadata = {
  // Basic metadata
  title: {
    default: siteConfig.title,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: siteConfig.keywords,
  authors: [{ name: "stableAPY", url: "https://x.com/stableAPY" }],
  creator: "stableAPY",
  publisher: siteConfig.name,
  
  // Canonical URL
  metadataBase: new URL(siteConfig.url),
  alternates: {
    canonical: "/",
  },
  
  // Icons
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    apple: "/favicon.svg",
    shortcut: "/favicon.ico",
  },
  
  // Manifest for PWA
  manifest: "/manifest.json",
  
  // Open Graph - for Facebook, LinkedIn, Discord, etc.
  // Images are auto-generated by opengraph-image.tsx
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    title: siteConfig.title,
    description: siteConfig.description,
    siteName: siteConfig.name,
  },
  
  // Twitter Card - Images are auto-generated by twitter-image.tsx
  twitter: {
    card: "summary_large_image",
    title: siteConfig.title,
    description: siteConfig.description,
    creator: siteConfig.twitterHandle,
    site: siteConfig.twitterHandle,
  },
  
  // Robots
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  
  // Verification (add your own IDs when available)
  // verification: {
  //   google: "your-google-verification-code",
  // },
  
  // App-specific
  applicationName: siteConfig.name,
  category: "Finance",
  
  // Theme
  other: {
    "theme-color": "#00ff41",
    "color-scheme": "dark",
    "msapplication-TileColor": "#0a0e0f",
  },
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const headersList = await headers()
  const cookie = headersList.get("cookie")
  const initialState = cookieToInitialState(config, cookie)

  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.className} bg-[#0a0e0f] text-[#00ff41] antialiased`}>
        <Providers initialState={initialState}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
