import type React from "react"
import type { Metadata } from "next"
import { headers } from "next/headers"
import { cookieToInitialState } from "wagmi"
import Script from "next/script"

import "./globals.css"

import { Geist, Geist_Mono, Geist as V0_Font_Geist, Geist_Mono as V0_Font_Geist_Mono, Source_Serif_4 as V0_Font_Source_Serif_4 } from 'next/font/google'
import { Providers } from "./providers"
import { config } from "@/lib/wagmi/config"
import { generatePageToken } from "@/lib/api/token"
import { TokenProvider } from "@/components/token-provider"

// Initialize fonts
const _geist = V0_Font_Geist({ subsets: ['latin'], weight: ["100","200","300","400","500","600","700","800","900"] })
const _geistMono = V0_Font_Geist_Mono({ subsets: ['latin'], weight: ["100","200","300","400","500","600","700","800","900"] })
const _sourceSerif_4 = V0_Font_Source_Serif_4({ subsets: ['latin'], weight: ["200","300","400","500","600","700","800","900"] })

const geistSans = Geist({ subsets: ["latin"] })
const geistMono = Geist_Mono({ subsets: ["latin"] })

// Site configuration for SEO
const siteConfig = {
  name: "Hyperfolio",
  // Title optimized for 50-60 characters (currently 56)
  title: "Hyperfolio | HyperEVM Multi-Wallet DeFi Portfolio Tracker",
  // Description optimized for 100-130 characters (currently 118)
  description: "Track tokens, NFTs, DeFi positions & transactions across multiple wallets on HyperEVM. Real-time Hyperliquid analytics.",
  url: "https://hyperfolio.xyz",
  twitterHandle: "@stableAPY",
  keywords: [
    "HyperEVM",
    "Hyperliquid",
    "DeFi",
    "Portfolio Tracker",
    "Crypto Portfolio",
    "NFT Tracker",
    "Wallet Tracker",
    "Multi-wallet",
    "Token Tracking",
    "DeFi Dashboard",
    "Hyperbeat",
    "HYPE",
  ],
  // Social links
  socials: {
    twitter: "https://x.com/stableAPY",
  },
}

export const metadata: Metadata = {
  // Basic metadata
  title: {
    default: siteConfig.title,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: siteConfig.keywords,
  authors: [{ name: "stableAPY", url: "https://x.com/stableAPY" }],
  creator: "stableAPY",
  publisher: siteConfig.name,
  
  // Canonical URL
  metadataBase: new URL(siteConfig.url),
  alternates: {
    canonical: "/",
  },
  
  // Icons
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    apple: "/favicon.svg",
    shortcut: "/favicon.ico",
  },
  
  // Manifest for PWA
  manifest: "/manifest.json",
  
  // Open Graph - for Facebook, LinkedIn, Discord, etc.
  // Images are auto-generated by opengraph-image.tsx
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    title: siteConfig.title,
    description: siteConfig.description,
    siteName: siteConfig.name,
  },
  
  // Twitter Card - Images are auto-generated by twitter-image.tsx
  twitter: {
    card: "summary_large_image",
    title: siteConfig.title,
    description: siteConfig.description,
    creator: siteConfig.twitterHandle,
    site: siteConfig.twitterHandle,
  },
  
  // Robots
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  
  // Verification (add your own IDs when available)
  // verification: {
  //   google: "your-google-verification-code",
  // },
  
  // App-specific
  applicationName: siteConfig.name,
  category: "Finance",
  
  // Theme
  other: {
    "theme-color": "#00ff41",
    "color-scheme": "dark",
    "msapplication-TileColor": "#0a0e0f",
  },
}

// JSON-LD Structured Data for SEO
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${siteConfig.url}/#organization`,
      name: siteConfig.name,
      url: siteConfig.url,
      logo: {
        "@type": "ImageObject",
        url: `${siteConfig.url}/favicon.svg`,
      },
      sameAs: [
        siteConfig.socials.twitter,
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${siteConfig.url}/#website`,
      url: siteConfig.url,
      name: siteConfig.name,
      description: siteConfig.description,
      publisher: {
        "@id": `${siteConfig.url}/#organization`,
      },
      inLanguage: "en-US",
    },
    {
      "@type": "WebApplication",
      "@id": `${siteConfig.url}/#webapp`,
      name: siteConfig.name,
      description: siteConfig.description,
      url: siteConfig.url,
      applicationCategory: "FinanceApplication",
      operatingSystem: "Any",
      browserRequirements: "Requires JavaScript",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
      },
      featureList: [
        "Multi-wallet portfolio tracking",
        "Real-time token balances",
        "NFT collection management",
        "DeFi position monitoring",
        "Transaction history",
        "HyperEVM blockchain support",
      ],
      creator: {
        "@id": `${siteConfig.url}/#organization`,
      },
    },
    {
      "@type": "SoftwareApplication",
      name: siteConfig.name,
      applicationCategory: "DeFi Portfolio Tracker",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
      },
      aggregateRating: {
        "@type": "AggregateRating",
        ratingValue: "4.8",
        ratingCount: "100",
        bestRating: "5",
        worstRating: "1",
      },
    },
  ],
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const headersList = await headers()
  const cookie = headersList.get("cookie")
  const userAgent = headersList.get("user-agent")
  const initialState = cookieToInitialState(config, cookie)
  
  // Generate signed API token for client-side requests
  const apiToken = generatePageToken(userAgent)

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Google Tag Manager */}
        <Script
          id="gtm"
          strategy="afterInteractive"
        >
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-K8ZG67BR');`}
        </Script>
        {/* Google Analytics */}
        <Script
          id="ga"
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-TCD5G3MPGQ"
        />
        <Script id="ga-config" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-TCD5G3MPGQ', {
              send_page_view: true
            });
          `}
        </Script>
        {/* JSON-LD Structured Data for rich snippets */}
        <Script
          id="json-ld"
          type="application/ld+json"
          strategy="beforeInteractive"
        >
          {JSON.stringify(jsonLd)}
        </Script>
      </head>
      <body className={`${geistSans.className} bg-background text-foreground antialiased`}>
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-K8ZG67BR"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
            title="Google Tag Manager"
          />
        </noscript>
        <Providers initialState={initialState}>
          <TokenProvider initialToken={apiToken} />
          {children}
        </Providers>
      </body>
    </html>
  )
}
